name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          override: true
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v2.0.0/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Start Solana validator
        run: solana-test-validator --quiet &
      - name: Run tests
        run: cargo test --all-features
      - name: Check test coverage
        run: cargo tarpaulin --out Html
      - name: Build
        run: cargo build --release